POST https://localhost:5001/api/auth/login
Content-Type: application/json

{
    "username":"admin",
    "password":"@dm1n@pp"
}

### Create Org Category
POST https://localhost:5001/api/organizationcategories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlcyI6WyJVc2VyLlVwZGF0ZSIsIlVzZXIuUmVhZCIsIlJvbGUuRGVsZXRlIiwiUm9sZS5SZWFkIiwiRGFzaGJvYXJkIiwiTWVzc2FnZVBvcnRhbCIsIlJvbGUuQ3JlYXRlIiwiU2V0dGluZyIsIlJlcG9ydCIsIlJvbGUuVXBkYXRlIiwiQWRtaW5pc3RyYXRpb24iLCJVc2VyLkRlbGV0ZSIsIlVzZXIuQ3JlYXRlIl0sInVzZXJuYW1lIjoiQWRtaW4iLCJlbWFpbCI6ImluZm9AYXBwLmNvbSIsInBob25lTnVtYmVyIjoiMDAwMDAwMDAwMCIsImZ1bGxOYW1lIjoiQWRtaW5pc3RyYXRvciIsInBpY3R1cmUiOiIiLCJleHAiOjE2MTcxNDEyMDksImlzcyI6InN1cHBvcnRfaHViX2NvcmUuZGV2bmVzdHN5c3RlbXMuY29tIiwiYXVkIjoic3VwcG9ydF9odWJfY29yZS5kZXZuZXN0c3lzdGVtcy5jb20ifQ.zRReYzXIQnGWJsVl8t4GBWCBNkikhHAvMZNI09L0C4o

{
    "name":"General"
}


### Fetch;// All Category
GET https://localhost:5001/api/organizationcategories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlcyI6WyJVc2VyLlVwZGF0ZSIsIlVzZXIuUmVhZCIsIlJvbGUuRGVsZXRlIiwiUm9sZS5SZWFkIiwiRGFzaGJvYXJkIiwiTWVzc2FnZVBvcnRhbCIsIlJvbGUuQ3JlYXRlIiwiU2V0dGluZyIsIlJlcG9ydCIsIlJvbGUuVXBkYXRlIiwiQWRtaW5pc3RyYXRpb24iLCJVc2VyLkRlbGV0ZSIsIlVzZXIuQ3JlYXRlIl0sInVzZXJuYW1lIjoiQWRtaW4iLCJlbWFpbCI6ImluZm9AYXBwLmNvbSIsInBob25lTnVtYmVyIjoiMDAwMDAwMDAwMCIsImZ1bGxOYW1lIjoiQWRtaW5pc3RyYXRvciIsInBpY3R1cmUiOiIiLCJleHAiOjE2MTcxNDEyMDksImlzcyI6InN1cHBvcnRfaHViX2NvcmUuZGV2bmVzdHN5c3RlbXMuY29tIiwiYXVkIjoic3VwcG9ydF9odWJfY29yZS5kZXZuZXN0c3lzdGVtcy5jb20ifQ.zRReYzXIQnGWJsVl8t4GBWCBNkikhHAvMZNI09L0C4o